//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace falabellaSeguros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class compania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public compania()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int compania_Id { get; set; }

        [Required]
        [Display(Name = "Nombre Compañia")]
        public string compania_Nombre { get; set; }
        [Required]
        [Display(Name = "Dirección Compañia")]
        public string compania_Direccion { get; set; }
        [Required]
        [Display(Name = "Telefono Compañia")]
        public decimal compania_Telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto { get; set; }
    }
}
