//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace falabellaSeguros.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.venta = new HashSet<venta>();
        }
    
        public int producto_Id { get; set; }
        [Required]
        [Display(Name ="Nombre Producto")]
        public string producto_Nombre { get; set; }
        [Required]
        [Display(Name = "Tipo Producto")]
        public int producto_Tipo { get; set; }
        [Required]
        [Display(Name = "Compañia ofertora")]
        public int producto_Compania { get; set; }
    
        public virtual compania compania { get; set; }
        public virtual tipoProd tipoProd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<venta> venta { get; set; }
    }
}
